CLASS /dmo/bp_bookingsupplement_u25 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /dmo/i_travel_u25 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /dmo/bp_bookingsupplement_u25 IMPLEMENTATION.
ENDCLASS.
